### ISSUE TITLE
Exception has occured, maybe you didn't reply to MidJourney message

### ISSUE THREAD

**Issue by arwooy** [Wildric-Auric/MidJourney-Wrapper#10]
I did reply the message, still got this error.  
Exception has occured, maybe you didn't reply to MidJourney message
I debug it found:
Globals.targetHash = str((message.reference.resolved.attachments[0].url.split("_")[-1]).split(".")[0])
message.reference.resolved.attachments is empty.

The second error is:
 I modifed guild_id to my server id. it can send message and get the results in Salai , but  still get error when started.  
discord.errors.HTTPException: 405 Method Not Allowed (error code: 0): 405: Method Not Allowed,

**Comment by Wildric-Auric** [comment]
Well, as the error says it you target a midjourney message which does not an attachment. Don't you?

**Comment by Wildric-Auric** [comment]
It's fixed now, look at #11.
