### ISSUE TITLE
unknown guild  error 10004

### ISSUE THREAD

**Issue by mjh1b** [Wildric-Auric/MidJourney-Wrapper#11]
Hi, 
 I have checked the other github post with this error, however I can't resolve this 
{"message": "Unknown Guild", "code": 10004}

I have checked the Globals.py file and made sure that the IDs are correct and Tokens are correct. 

So just to be clear
 I can do /mj_imagine cyberpunk tokyo 
 
  Then it loads 
   Then it says 
Request has failed; please try later
In terminal I see {"message": "Unknown Guild", "code": 10004}

How do I fix this?

Thank you!

**Comment by mjh1b** [comment]
I have now resolved this. please update your main repo so that salai.py has this 
"guild_id":Globals.SERVER_ID,
    "channel_id":Globals.CHANNEL_ID,
    
    as previously it uses hardcoded values (this is causing the above error) 
    
    Thank you!!

**Comment by Wildric-Auric** [comment]
Sorry, I did that temporarly (hence a TODO comment if you noticed) but forgot to fix it. Thank you!

**Comment by Wellmare** [comment]
I am getting this error now, although the code should be corrected
