### ISSUE TITLE
Unknown Integration Code 10005

### ISSUE THREAD

**Issue by BoredMind** [Wildric-Auric/MidJourney-Wrapper#15]
Running the bot works but using slash commands returns this error.  Any suggestions? 

<Response [400]>
{"message": "Unknown Integration", "code": 10005}

**Comment by Wildric-Auric** [comment]
Try updating pycord

**Comment by BoredMind** [comment]
Never mind, it's still happening.  Using py-cord 2.3.2 or  py-cord-2.0.0b1.  Both return that error.  It worked 1 time at 2.0.0b1 but only once. 

Using 2.0.0b1 I also see this error on start up:

`discord.errors.HTTPException: 405 Method Not Allowed (error code: 0): 405: Method Not Allowed`

I do not get it on 2.3.2

**Comment by Wildric-Auric** [comment]
I'm going to test the bot and try to fix it soon

**Comment by Wildric-Auric** [comment]
I tried the bot today, and it seems that can't reproduce the error, everything works fine for me.

**Comment by Wildric-Auric** [comment]
Actually, you are still getting "Unknown Integration" right?

**Comment by BoredMind** [comment]
Correct, still see that in response.text output

**Comment by BoredMind** [comment]
Fixed the response.text error from the other issue #14 by manually changing it for now but still seeing unknown integration.

**Comment by Wildric-Auric** [comment]
ok I see, I never saw this error and discord API documentation does not help me with. Have double checked your account token, channel id and server id?

**Comment by BoredMind** [comment]
I have triple-checked the server/channel IDs and bot token, I blew away the repo and started fresh in a virtual environment for Python, and I've grabbed the user token from both Firefox and Chrome.

I tried using known bad user tokens as well and got this result:

```
python3 main.py
Logged in as Bot####
{"message": "401: Unauthorized", "code": 0}
401
```

**Comment by Wildric-Auric** [comment]
I searched many time about that error but could not find anything, sorry.
Since I cannot reproduce it I would  simply suggest to try on another account and another server. If that works I would not know why; it may involve something beyond the documentation...

**Comment by Wildric-Auric** [comment]
Sorry to ask that but is MidJourney bot in the server?

**Comment by BoredMind** [comment]
> Sorry to ask that but is MidJourney bot in the server?

It is not in the server.   I added it and now it works.  I don't know how I missed this step.  I guess I assumed the Discord bot that I created would relay everything from MJ.  Wow, sorry about all this!

**Comment by Wildric-Auric** [comment]
Yeah I knew it by seeing that integration are bots among other stuff, unknown  integration means that you were giving the bot id which he couldn't find in the server.

**Comment by xucian** [comment]
hello! 
I updated py-coord to 2.4.1 and I still get the issue (though I don't get a 405: Method Not Allowed error anymore).
tried removing and re-adding the bot to the server, while also resetting its token. 
still getting:
```
{"message": "Unknown Integration", "code": 10005}
400
```

**Comment by Dooy** [comment]
> hello! I updated py-coord to 2.4.1 and I still get the issue (though I don't get a 405: Method Not Allowed error anymore).
> 
> * tried removing and re-adding the bot to the server, while also resetting its token.
> * tried setting it to both private and public (not ideal)
> * tried creating another bot
> 
> in all cases, still getting:
> 
> ```
> {"message": "Unknown Integration", "code": 10005}
> 400
> ```

SALAI_TOKEN = [Token of the Account from which you paid MidJourney ]


Have you ever paid for your Account?
