### ISSUE TITLE
Request has failed; please try later

### ISSUE THREAD

**Issue by Kliffh** [Wildric-Auric/MidJourney-Wrapper#16]
Hello, the bot always take the response:  "Request has failed; please try later" since 2023.02.04. 
It joined the server but on console there has no print line of "Logged in as {bot.user}".

**Comment by Wildric-Auric** [comment]
I see, thanks for reporting this, I'm going to test the bot soon and try to fix that

**Comment by Kliffh** [comment]
> I see, thanks for reporting this, I'm going to test the bot soon and try to fix that

Get it passed sir, the last salai_token seems expired. Renew and it works! 
Thanks, good day!~~~
