### ISSUE TITLE
Cant seem to fix this error 405

### ISSUE THREAD

**Issue by Damply** [Wildric-Auric/MidJourney-Wrapper#2]
Getting this error. Cant seem to fix it, gives requests has failed in chat when trying to imagine.

`Ignoring exception in on_connect
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "C:\Python310\lib\site-packages\discord\bot.py", line 793, in on_connect
    await self.register_commands()
  File "C:\Python310\lib\site-packages\discord\bot.py", line 460, in register_commands
    await self.http.bulk_upsert_command_permissions(
  File "C:\Python310\lib\site-packages\discord\http.py", line 338, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 405 Method Not Allowed (error code: 0): 405: Method Not Allowed`

**Comment by Wildric-Auric** [comment]
Seems like a pycord problem. Did you install pycord *version* specified in requirements? Are you using a virtual environment?
I found an [issue](https://github.com/Pycord-Development/pycord/issues/1349) in pycord github page which is exactly yours, take a look on it.
If it still does not work, try changing pycord version to match master branch in their repository. Tell me if the problem is solved.

**Comment by Damply** [comment]
i originally installed the version from req.txt, uninstalling that and upgrading to the newest from the master branch fixed the 405 error. I'm still getting the "Request has failed; please try later"

I've put everything correctly into Globals as far as I can tell. Should i worry about changing session id in Salai?

**Comment by Damply** [comment]
Added a print to see what the response is, in discord network its sending the post request with 204 code but in powershell i see it responding with 400. Not sure why, everything seems correct

**Comment by Wildric-Auric** [comment]
Okay now the first issue is solved. You have a second issue with the account sending request to MidJourney.
Did you already activated that account for MidJourney, I mean going to write manually /imagine from this account and accepting rules and terms of use. But I'm pretty sure you already did.
For the session id I think it's a random number generated each session, you can use just one without problem I think.
I'm going to try to get what's the origin of the issue.

**Comment by Damply** [comment]
Yeah i use midjourney already, works fine in their server and in dm's with the bot. Super odd why its giving 400 error, i honestly have no idea why its giving a 400 error

**Comment by Wildric-Auric** [comment]
I think it's due to application_id, it's user dependent even though I thought it was related to midjourney bot, I'm going to see if that's true and make a commit fixing this.

**Comment by Damply** [comment]
My application_id is the same as the one you put in, i checked all those values already to see if theres a mismatch but they are all the same in the post request from the normal midjourney request

**Comment by Wildric-Auric** [comment]
No I was wrong sorry application id is midjourney id.

**Comment by Damply** [comment]
`<Response [400]>
--------------------------------------
{'authorization': 'my midjourney token'}
--------------------------------------
{'type': 2, 'application_id': '936929561302675456', 'guild_id': 'my server id', 'channel_id': 'my channel id', 'session_id': 'EDCwWeQaKTt8iHRX8DUIFinQFlgUM2ra', 'data': {'version': '994261739745050686', 'id': '938956540159881230', 'name': 'imagine', 'type': 1, 'options': [{'type': 3, 'name': 'prompt', 'value': 'testing'}], 'application_command': {'id': '938956540159881230', 'application_id': '936929561302675456', 'version': '994261739745050686', 'default_permission': True, 'default_member_permissions': None, 'type': 1, 'name': 'imagine', 'description': 'There are endless possibilities...', 'dm_permission': True, 'options': [{'type': 3, 'name': 'prompt', 'description': 'The prompt to imagine', 'required': True}]}, 'attachments': []}}`

`sessionID = "".join(random.choice(string.ascii_letters + string.digits) for _ in range(32))`

i have it random generating session ID's too just in case it was the issue. I dont see what i am missing, it sends the post request in the discord traffic but 400's on my end. Right now skipping the discord bot part and just sending the request in cmd.

**Comment by Wildric-Auric** [comment]
To simulate your experience. I put the first function in salai.py in a separate file and tried it on two different servers with two different accounts. It worked correctly. So it's sure that the issue is either from your network or account (I don't really know how does networking work precisely here). I remember that during some tests I had problems because of an account which wasn't verified in discord. Is this the case of your account? If this does not solve the problem I don't see why it is working for my accounts but not in your case...

**Comment by Wildric-Auric** [comment]
Also double (triple?) check Salai Token

**Comment by Damply** [comment]
I dont have a number or 2factor enabled on my discord account but its been verified for many years now. Will add those two and see if it fixes anything. I've checked the Salai token so many times expecting to have an error there but its correct.

**Comment by Damply** [comment]
OKAY so i got it working, its generating the image but it does not embed it into my server chat. I get the "your image is being prepared" never updates past that

**Comment by mbledkowski** [comment]
> Never mind fixed everything. thanks for the help!

How did you fix it?
