### ISSUE TITLE
Using MidJourney's Bot command in our own bot like DaVinci

### ISSUE THREAD

**Issue by hassan-suriya** [Wildric-Auric/MidJourney-Wrapper#20]
I created my own bot and added MidJourney's bot to my server's channel. I am creating my application in Java using JDA Library. When my bot sends message to the channel in which MidJourney's bot exists, it does not recognize my bot's command (such as /imagine [prompt]". How do I make it like DaVinci bot as yours which recognizes  MidJourney's bot commands and executes those command like yours. 
Thank You.

**Comment by Wildric-Auric** [comment]
Slash command requests are rather interactions than simple messages, it means they are specially treated by Discord API not just parsed like you would do with old command implementation in Discord. In Salai.py I deal with this when I send a request with a specific payload that I found by watching "network" on my browser. If you weren't just sending messages to the channel, and have another issue, feel free to ask again.
