### ISSUE TITLE
Feature Request: Multiple Channels

### ISSUE THREAD

**Issue by Pharrcyde** [Wildric-Auric/MidJourney-Wrapper#21]
Hello!
When I utilize 'DaVinci' in a different channel, the 'other bot' generates the content and only displays it in the designated channel specified in the Globals.py file. However, I'm curious if it's possible to expand the bot's functionality by enabling it to show the content in multiple permitted channels. Specifically, it would be ideal if the bot could display the generated content in the same channel where the /mj_imagine command was initiated. Would it be possible to implement this feature?

**Comment by Wildric-Auric** [comment]
It was implemented in my last commit 286b26dcbe6d9cff48e4dc905e7f6b4239d7dea8. To enable this feature you will have to set ```USE_MESSAGED_CHANNEL``` [Globals.py](https://github.com/Wildric-Auric/MidJourney-Wrapper/blob/main/Globals.py) to True.
*Note that upscaling images should be done in the same channel. If you use the bot with the variable set on true and then switch to false, you can't upscale images published in channels different from the one you chose. But this should not be a problem if you plan to always use the feature.*
Make me know, after testing, if everything is ok.

**Comment by Pharrcyde** [comment]
Just wanted to let you know that everything has been running smoothly for the past couple of days. Thank you for your work on this - it's much appreciated!

**Comment by Pharrcyde** [comment]
> It was implemented in my last commit [286b26d](https://github.com/Wildric-Auric/MidJourney-Wrapper/commit/286b26dcbe6d9cff48e4dc905e7f6b4239d7dea8). To enable this feature you will have to set `USE_MESSAGED_CHANNEL` [Globals.py](https://github.com/Wildric-Auric/MidJourney-Wrapper/blob/main/Globals.py) to True. _Note that upscaling images should be done in the same channel. If you use the bot with the variable set on true and then switch to false, you can't upscale images published in channels different from the one you chose. But this should not be a problem if you plan to always use the feature._ Make me know, after testing, if everything is ok.

Just wanted to let you know that everything has been running smoothly for the past couple of days. Thank you for your work on this - it's much appreciated!
