### ISSUE TITLE
Midjourney token

### ISSUE THREAD

**Issue by ondraasek** [Wildric-Auric/MidJourney-Wrapper#22]
Hey, where to get midjourney token? SALAI?
I went thru my whole account and didnt find it. I paid for the acc thanks a lot

**Comment by ondraasek** [comment]
probably found it as ID - long number

**Comment by Wildric-Auric** [comment]
It is not the ID, it is a a string of numbers and letters check #18 where I reference this [article](https://www.androidauthority.com/get-discord-token-3149920/).
*Otherwise you  ccould just google "How to get your discord token" to find a way to do so*
And by the way there is nothing called "midjourney token" here.

**Comment by ondraasek** [comment]
I figured it out, thanks a lot! May I ask you one more Q? Is possible to call this /mj_imagine from thru API? If I tried it its send like normal chat message, but is possible to call command? thanks a lot

**Comment by ondraasek** [comment]
or if you can just give me a hint what I should to use? message component? Or is it slash command? thanks a lot

**Comment by Wildric-Auric** [comment]
It is a slash command here, you would need to make a request as a slash command like I do in Salai.py. Otherwise you could, instead of having slash command in main.py, use the same code while listenning to messages with discord's bot.

**Comment by nihs269** [comment]
> It is not the ID, it is a a string of numbers and letters check #18 where I reference this [article](https://www.androidauthority.com/get-discord-token-3149920/). _Otherwise you ccould just google "How to get your discord token" to find a way to do so_ And by the way there is nothing called "midjourney token" here.

What type of this token?? DAVINCI_TOKEN or SALAITOKEN??
