### ISSUE TITLE
Error code 50035, INTERACTION_APPLICATION_COMMAND_INVALID_VERSION

### ISSUE THREAD

**Issue by Emty0105** [Wildric-Auric/MidJourney-Wrapper#26]
Hi everybody,

A few days ago I called the API fine, until today I am getting error 

Code 50035, INTERACTION_APPLICATION_COMMAND_INVALID_VERSION, 
"message": "This command is outdated, please try again in a few minutes".

I guess it is due to 2 param: session_id and version change.
If anyone has solved it, please guide me
Thanks

<img width="729" alt="Screenshot 2023-02-23 at 21 57 37" src="https://user-images.githubusercontent.com/16770989/220944351-040ee949-aafd-4196-b988-c68930cb8362.png">

**Comment by Pharrcyde** [comment]
I've also encountered an issue where the bot's functionality has stopped working for me, except for the /hello command. Attempts to get it to interact with the other bot have been unsuccessful. I hope this issue can be resolved soon.🤞

**Comment by Wildric-Auric** [comment]
Thank you for having reported this issue as soon as it has appeared. I think it's solved, feel free to test.
*I did not ran all needed tests, if the issue persists, please reopen this thread*

**Comment by Emty0105** [comment]
> Thank you for having reported this issue as soon as it has appeared. I think it's solved, feel free to test. _I did not ran all needed tests, if the issue persists, please reopen this thread_

My problem has been solved. Thank you so much for your help

**Comment by Pharrcyde** [comment]
I appreciate your prompt and effective support.
 It works beautifully now.
Cheers!

**Comment by Pharrcyde** [comment]
I appreciate your prompt and effective support! It works beautifully now.
Cheers!
