### ISSUE TITLE
AutoUpscale function

### ISSUE THREAD

**Issue by krixoko** [Wildric-Auric/MidJourney-Wrapper#27]
I would like too see an option to auto uposcale generated images.

AutoUpscale = True

**Comment by rendercyprus** [comment]
is MidJourney-Wrapper working now?

**Comment by infermi** [comment]
you can create it by yourself, you can listen in on_message for replies in the channel you configured in the globals.py for messages by midjourney with images, and get their id and job id and give it to the upscale in salai.py. i can show you how i did it in my server.

**Comment by Wildric-Auric** [comment]
It won't be implemented, not now at least.
