### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by DevMarkosM** [Wildric-Auric/MidJourney-Wrapper#29]
Hi i think its need update again , i have same issue error 401 after update ^^ thank you :)

**Comment by Wildric-Auric** [comment]
I've just tested, and it works well. Double check your tokens.

**Comment by DevMarkosM** [comment]
idk what is wrong with me :/ but my tokens should work

**Comment by Wildric-Auric** [comment]
Well, when do you get the error? Does the bot (DaVinci) connect? Do /hello command work? I need more info to help...

**Comment by DevMarkosM** [comment]
i get this error when i try to generate image with  print ->  response.status_code, when i print -> response.txt , i get nil value no exist   , yes the /hello working fine , config picture : https://i.imgur.com/hGA45o3.png

**Comment by Wildric-Auric** [comment]
"Nil value"? Can I see the output of response.text?

**Comment by DevMarkosM** [comment]
yes sure ^^ https://i.imgur.com/e5B78iO.png

**Comment by Wildric-Auric** [comment]
It's ```response.text``` not *txt*...

**Comment by DevMarkosM** [comment]
oh okay sry its because in your code its written .txt now i get this : https://i.imgur.com/nP5X9SD.png ^^

**Comment by Wildric-Auric** [comment]
[401](https://discord.com/developers/docs/topics/opcodes-and-status-codes) means that ```The Authorization header was missing or invalid.``` which means that there is a problem with the token. If it used to work before, you would want to check if your account token has changed.

**Comment by DevMarkosM** [comment]
hmm okay thank you maybe its a midjourney problem because i have try to change my api key 3 time and i have standard plan :/ it should work , i will try to contact midjourney support , thank you for your help ^^

**Comment by DevMarkosM** [comment]
hmm okay thank you i will check :)

**Comment by DevMarkosM** [comment]
i have tried to change my tokens but nothing :/ idk

**Comment by Wildric-Auric** [comment]
okay I see. I don't know why for now... 
Just to be sure, how do you get your "Salai" token?

**Comment by DevMarkosM** [comment]
Oh i think i see , Salai token its the discord account token ans not the midjourney api ? Because i have see in your code you login with this token bruh my bad x) , i have put api instead the token … sry for distrub you and thank you

**Comment by Wildric-Auric** [comment]
I said it in the readme but maybe it's not clear enough you're the second person to make this mistake, I will maybe give better precision in the readme. You're welcome.

**Comment by soniked** [comment]
Hello. Sorry for little offtop, but i have similar problem.
I am trying to test this script, and run it on replit. But commands on salai-side doesnt work.
When im logging in - he writes me next error:
`Ignoring exception in on_connect
Traceback (most recent call last):
  File "/home/runner/EmbellishedKookyMultithreading/venv/lib/python3.10/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/home/runner/EmbellishedKookyMultithreading/venv/lib/python3.10/site-packages/discord/bot.py", line 793, in on_connect
    await self.register_commands()
  File "/home/runner/EmbellishedKookyMultithreading/venv/lib/python3.10/site-packages/discord/bot.py", line 460, in register_commands
    await self.http.bulk_upsert_command_permissions(
  File "/home/runner/EmbellishedKookyMultithreading/venv/lib/python3.10/site-packages/discord/http.py", line 338, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 405 Method Not Allowed (error code: 0): 405: Method Not Allowed`
On the bot's side (DaVinci) everything is ok.

Yesterday it didn't want to work and doesn't accept the commands (accepts only usual messages and $mj_target).
Today i tried to change SALAI account and his token - and it starts to work, but upper error on login still standing. Is it ok?

**Comment by Wildric-Auric** [comment]
@soniked I noticed a while ago that on linux it does this, try updating Pycord (take a look at [this](https://github.com/Pycord-Development/pycord/issues/1349) by the way), if the problem persists it is not a big issue for now since it has  no repercussion of the functionning of the program.

**Comment by soniked** [comment]
@Wildric-Auric, thank you
And the last question.(
I read that self-bots (automate the non-bot user) on discord are restricted now and may result in blocking of account ([link](https://support.discord.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-)).
Is your project affected by this rule or no?

**Comment by Wildric-Auric** [comment]
Yes it is forbidden. But as long as you don't servers and messages it should be fine I think. Till now, no case of account blocking was reported.
