### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by wdzxs** [Wildric-Auric/MidJourney-Wrapper#3]
i use java，but have Unauthorized error， i dont know why， please

**Comment by wdzxs** [comment]
SALAI_TOKEN  is member id？

**Comment by wdzxs** [comment]
sorry，i know how to fix it，thanks

**Comment by kuyin** [comment]
Hey 兄弟我看到你之前提了这个问题，请问现在我的upscale和variation命令不起作用，你的还能用吗？
