### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by MelodieAnge** [Wildric-Auric/MidJourney-Wrapper#30]
Hiii , i'm trying your bot but when i try to generate image , i got this error {"message": "Unknown Integration", "code": 10005}
400 , if you can help me it would be really nice .

Thank you .

**Comment by Wildric-Auric** [comment]
It's a duplicate of issue #15; 
you should have the official midjourney [bot](https://docs.midjourney.com/docs/invite-the-bot) in the same server, like said in the readme.

**Comment by MelodieAnge** [comment]
thank you
