### ISSUE TITLE
Setting parameters

### ISSUE THREAD

**Issue by Yishto** [Wildric-Auric/MidJourney-Wrapper#35]
Where to get the" SALAI_TOKE "? Would you like a screenshot or detailed explanation? Thank you.

**Comment by bhj8** [comment]
On the midjourney official website, on the subscription page, there is a manage button, click on it and you can go to query "SALAI_TOKE".
I'm also subscribed, but I can't open this page. Always display "An error 500 occurred on server.". I asked some subscribers, and they couldn't open it properly either. I suspect that midjourney has already known this method and blocked the page for querying API keys. (this behavior will not affect any normal users)
I'm also stuck, if anyone can solve it, please let me know, very much.

**Comment by bhj8** [comment]
Maybe we can find our own API keys by grabbing the request packet. But I don't know anything about the mechanics of discord. It would be great if someone could solve it

**Comment by bhj8** [comment]
好的，我已经成功拿到了“SALAI_TOKE” ，请参阅[https://github.com/Wildric-Auric/MidJourney-Wrapper/issues/22](url)
