### ISSUE TITLE
Request has failed; please try later & Name Error 

### ISSUE THREAD

**Issue by Valentine8342** [Wildric-Auric/MidJourney-Wrapper#36]
The bot's hello command works fine on the server but when I try the imagine command I get a request has failed, try again later error.
 
![error](https://user-images.githubusercontent.com/72111168/227738956-7bf95f86-89cf-4775-b4fa-417abf8b5f6b.png)

Also my tokens have periods in them (.) causing a name error

![image](https://user-images.githubusercontent.com/72111168/227738901-4c89a1ca-d5cf-4044-99a8-61d07dc72dad.png)

Those aren't my full values, I removed several characters to protect my information. Apparently the (.) is causing some problems with my tokens being read correctly. Do I need to format them in a certain way?

**Comment by Wildric-Auric** [comment]
It's a string; put your token between double quotes, and there are no brackets.
