### ISSUE TITLE
how to set up global settings?

### ISSUE THREAD

**Issue by yanxiang007** [Wildric-Auric/MidJourney-Wrapper#37]
Hi, I am new here. I have questions about how to find kinds of IDs that needed to be filled in global.py.

DAVINCI_TOKEN = [Token of Discord bot] ##where to find this token?

SERVER_ID = [Server id here] ##where to find this ID?

SALAI_TOKEN = [Token of the Account from which you paid MidJourney ] ## solved through other post

CHANNEL_ID = [Channel in which commands are sent] ##where to find this ID?

Besides, how to invite DAVINCI Bot to my server on Discord Website

**Comment by Wildric-Auric** [comment]
Using this project supposes that you know how discord bots work. 
Check this [link](https://www.ionos.com/digitalguide/server/know-how/creating-discord-bot/) to know how to create a bot, invite it to the server and get its token.

Once, you activate the developper mode (like said in the article) you can right click the channel and you can copy the channel ID. Same for ID of the server (which discord calls guildID).

**Comment by yanxiang007** [comment]
thanks a lot! I have already solved this problem follow your instruction.
