### ISSUE TITLE
443 ssl exceptions

### ISSUE THREAD

**Issue by carlchou00** [Wildric-Auric/MidJourney-Wrapper#38]
i keep receiving these exceptions, Mac OS
  and i dont know how to fix it

raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Connect call failed ('199.59.149.238', 443)]

**Comment by Wildric-Auric** [comment]
It's rather a discord api problem. Check this: https://github.com/Rapptz/discord.py/issues/4159
To reference a user who responded there:
`"If you're on macOS you'll want to go into the python 3.x folder in your Applications and double click Install Certificates.command"`

**Comment by carlchou00** [comment]
thanks, i already checked the link you provided before i open this issue, but it doesnt work for me either

**Comment by carlchou00** [comment]
still the same :(
thanks anyway, i will keep searching solutions until i fix it

**Comment by carlchou00** [comment]
i fix the problem by using proxy in main.py, like this:
`bot = discord.Bot(intents=discord.Intents.all(),proxy="http://127.0.0.0:port")`

in case someone need it
