### ISSUE TITLE
no image return 

### ISSUE THREAD

**Issue by carlchou00** [Wildric-Auric/MidJourney-Wrapper#39]
<img width="507" alt="Screenshot 2023-03-29 at 11 43 53" src="https://user-images.githubusercontent.com/13175918/228421440-e074c592-c736-4703-b9f7-a64a2ec4cf87.png">

few hours passed, and i got nothing back, what's happening?

**Comment by Wildric-Auric** [comment]
First thing: Make the same prompt with just the normal midjourney bot. Does it work?

**Comment by carlchou00** [comment]
thanks, unpaid user cannot send command, that's the reason why no image returned
