### ISSUE TITLE
Upscaling doesn't work due to additional string from Midjourney

### ISSUE THREAD

**Issue by galevy88** [Wildric-Auric/MidJourney-Wrapper#4]
Hi Oussama,

I opened this issue as you asked for raising the current issue with Midjourney Upscaling feature.
Till now, as you told me, the following data payload was required for generating new Upscale interaction requests:
`"custom_id":f"MJ::JOB::upsample::{index}"` 
When I tried to run this code I encounter a problem due to the fact that probably Midjourney included another piece of information that required for the payload. This string (red) is a specific identifier that represents an image that was created with /imagine command.
Notice that all 4 images that were generated by th /imagne / /mj_imagne command shared the same string
![image](https://user-images.githubusercontent.com/91119719/196289972-d972526a-b28b-4660-b712-e370d4ac72f7.png)

**Comment by Wildric-Auric** [comment]
fixed
