### ISSUE TITLE
Is there a method to execute commands such as/info and/fast, and receive a reply to a private message?

### ISSUE THREAD

**Issue by liustar1989** [Wildric-Auric/MidJourney-Wrapper#40]
I modified the code to use Python to operate Salai to execute commands, instead of using Davinci to listen and receive messages. However, I don't know how to make Salai send/info,/fast commands to Midjournal, and after manually sending the command, the returned information is only visible to individuals, and Davinci cannot listen to the returned information. Is there any good solution to this requirement?

**Comment by Wildric-Auric** [comment]
No there is no solution for this (at least known by me)

**Comment by bhj8** [comment]
I see the solution you need here, you can send commands to change fast and relax. Please refer to here to structure your request.
https://github.com/agentd00nut/midjourney-graph/blob/main/src/discord.py

But I'm still looking for a way to receive /info reply texts. (In the above code, info can be sent, but I haven't found traces of his use)
