### ISSUE TITLE
how to get 'a pair of message '

### ISSUE THREAD

**Issue by yslion** [Wildric-Auric/MidJourney-Wrapper#42]
when my bot send imagine prompt  to midjourney bot and midjourney bot  says 'Waiting to start'   called msg1 

when images are ready , midjourney bot  send the result  , called msg2  

except 'message.content' , is there any message's attribute  that can be able to match  each other  ?

many thanks

**Comment by bhj8** [comment]
Please see my latest issue
https://github.com/Wildric-Auric/MidJourney-Wrapper/issues/47
I guess our problem is essentially the same, I'm also trying to find this solution

**Comment by Wildric-Auric** [comment]
Since I listen to what's published on channels with the official discord bot, I think there is no way I can get those type of messages...

**Comment by yuexdang** [comment]
I haven't tested it, but Midjourney should be create the first time msg, the second time should be reply, I think it may support to judge whether the message is the first time or the second time by the state of the message. It only needs to construct different listening methods to get the content, and only needs ID to distinguish the sender's category. I am also trying to forward the message by listening, so as to support cross-platform robots
