### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'Bot'

### ISSUE THREAD

**Issue by arron123456** [Wildric-Auric/MidJourney-Wrapper#43]

**Comment by arron123456** [comment]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/38456883/230282083-4bf31fe3-1381-4033-aea1-775a70aac74a.png">

**Comment by arron123456** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/38456883/230285084-34776ee7-1364-4209-afe9-06366b62edf5.png">

**Comment by Wildric-Auric** [comment]
You don't have Pycoord installed?

**Comment by Wildric-Auric** [comment]
I think the issue is just you installed discord module instead of pycord.
