### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'Bot'

### ISSUE THREAD

**Issue by ebullienc3** [Wildric-Auric/MidJourney-Wrapper#46]
D:\Bots\midjourney>python bot.py
Traceback (most recent call last):
  File "D:\Bots\midjourney\bot.py", line 14, in <module>
    bot = discord.Bot()
          ^^^^^^^^^^^
AttributeError: module 'discord' has no attribute 'Bot'

**Comment by MikeJackOne** [comment]
> D:\Bots\midjourney>python bot.py Traceback (most recent call last): File "D:\Bots\midjourney\bot.py", line 14, in bot = discord.Bot() ^^^^^^^^^^^ AttributeError: module 'discord' has no attribute 'Bot'

Man. stop sending the issue,you should figure it out yourself

**Comment by bhj8** [comment]
> D:\Bots\midjourney>python bot.py Traceback（最近调用最后）： 文件“D:\Bots\midjourney\bot.py”，第 14 行，在 bot = discord.Bot() ^^^^^^ ^^^^^ AttributeError: 模块 'discord' 没有属性 'Bot'

You should try asking GPT first, after as much as possible can't be resolved. Ask another question.
The question you are asking now is simply wasting everyone's life

**Comment by Wildric-Auric** [comment]
You didn't install pycord correctly, and I think it's solved in anothe issue.
