### ISSUE TITLE
Receive messages rejected by mid

### ISSUE THREAD

**Issue by bhj8** [Wildric-Auric/MidJourney-Wrapper#47]
Sometimes, I accidentally send certain words, or repeatedly try to zoom in on the same picture. The mid robot will reply with a message that only subscribed accounts can see. Tell you what went wrong.
Is there currently a way to catch this message in python?

**Comment by bhj8** [comment]
I took /info as an example, checked all the request requests during this period, and found no request containing text information returning info.
And the text information of info was indeed displayed on the screen. This appears to be a different kind of message sent. (Messages rejected by Mid should also be sent in this way)

**Comment by Wildric-Auric** [comment]
I will answer it in #42
