### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'Bot'

### ISSUE THREAD

**Issue by Joe3160** [Wildric-Auric/MidJourney-Wrapper#49]
Traceback (most recent call last):
  File "D:\src\MidJourneyWrapper\main.py", line 5, in <module>
    bot = discord.Bot(intents=discord.Intents.all())
          ^^^^^^^^^^^
AttributeError: module 'discord' has no attribute 'Bot'

**Comment by Wildric-Auric** [comment]
Duplicate, look at #43
