### ISSUE TITLE
where SALAI_TOKEN?

### ISSUE THREAD

**Issue by hereww** [Wildric-Auric/MidJourney-Wrapper#52]
help!  I couldn't find where to obtain the SALAI_TOKEN

**Comment by charlesknapp** [comment]
You need to get your token from the account you're trying to use Midjourney with.

Find it in the headers of your client request.
Open inspector tools and view the Network tab. Filter by /api and you'll find it.

**Comment by Wildric-Auric** [comment]
See #18
