### ISSUE TITLE
What is "Token of the Account from which you paid MidJourney "

### ISSUE THREAD

**Issue by zgdhj95** [Wildric-Auric/MidJourney-Wrapper#56]
What is the 『Token of the Account from which you paid MidJourney 』？

I can't found the toke in modijourney.com.

**Comment by lingtalfi** [comment]
same issue here

**Comment by lingtalfi** [comment]
I believe I found it under midjourney.com > manage sub > Your standard plan > manage (little button) > manage api keys,
but unfortunately the midjourney.com website gives me an error 500 for now (out of luck)

**Comment by Wildric-Auric** [comment]
No it is not that! Check #18.
