### ISSUE TITLE
about Globals.py

### ISSUE THREAD

**Issue by brinkqiang** [Wildric-Auric/MidJourney-Wrapper#57]
DAVINCI_TOKEN = [Token of Discord bot]

SERVER_ID = [Server id here]

SALAI_TOKEN = [Token of the Account from which you paid MidJourney ]

CHANNEL_ID = [Channel in which commands are sent]
---------------------------------------------------------------------------------------------------------
I have read other posts but still haven't received any answers.

I need a rough parameter to let me know what these parameters look like. I will handle the rest myself.

Thank you

**Comment by 7catss** [comment]
me too

**Comment by nihs269** [comment]
Same proplem!!

**Comment by nihs269** [comment]
@Wildric-Auric

**Comment by hycao** [comment]
see this: https://github.com/Wildric-Auric/MidJourney-Wrapper/issues/18

**Comment by hycao** [comment]
I running it , and i create a issue in here : https://github.com/Wildric-Auric/MidJourney-Wrapper/issues/62
