### ISSUE TITLE
DAVINCI_TOKEN

### ISSUE THREAD

**Issue by nihs269** [Wildric-Auric/MidJourney-Wrapper#59]
I don't know what's DAVINCI_TOKEN and how to fix it in Globals.py. Pls help!

**Comment by ruhipilot** [comment]
is the same token of your Bot that create in Discord

**Comment by 7catss** [comment]
I get an error, can someone help me?
PS D:\CODE\MidJourney-Wrapper-main> & C:/Users/Administrator/AppData/Local/Programs/Python/Python311/python.exe d:/CODE/MidJourney-Wrapper-main/main.py
Traceback (most recent call last):
  File "d:\CODE\MidJourney-Wrapper-main\main.py", line 2, in <module>
    import Globals
  File "d:\CODE\MidJourney-Wrapper-main\Globals.py", line 3, in <module>
    DAVINCI_TOKEN =XX
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'XX' is not defined
PS D:\CODE\MidJourney-Wrapper-main>
