### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by nihs269** [Wildric-Auric/MidJourney-Wrapper#60]
In Windows system, I got a error "RuntimeError: Event loop is closed" when I run main.py. How to fix it??

**Comment by eemeetu** [comment]
How did you manage to fix it?

**Comment by nihs269** [comment]
> How did you manage to fix it?

First, you must create your bot and invite it to your chanel. Take the bot's token (check it carefully) and paste it in SALAI_TOKEN in Globals.py. This issue look like your SALAI_TOKEN was wrong!!
