### ISSUE TITLE
Is there any limit on the number of members I can use on a server?

### ISSUE THREAD

**Issue by yudu233** [Wildric-Auric/MidJourney-Wrapper#61]
Hello ! 

Thank you for your open source project！

I have a question ：

I subscribe to MJ membership. If I create a server and use the program, then all the members on my server can use MJ membership. Is there any limit on the number of members that can be used?

Because I will soon have a large number of friends to use, I am worried that the number of people will be limited！

**Comment by yuexdang** [comment]
no

**Comment by Wildric-Auric** [comment]
No
