### ISSUE TITLE
INTERACTION_APPLICATIO                                                                       N_COMMAND_INVALID_VERSION

### ISSUE THREAD

**Issue by ondraasek** [Wildric-Auric/MidJourney-Wrapper#82]
Hey, since today I have this problem.
{"code": 50035, "errors": {"data": {"_errors": [{"code": "INTERACTION_APPLICATIO                                                                       N_COMMAND_INVALID_VERSION", "message": "This command is outdated, please try aga                                                                       in in a few minutes"}]}}, "message": "Invalid Form Body"}
400
{"global": false, "message": "The resource is being rate limited.", "retry_after                                                                       ": 2.06}
429

any idea how to fix it thanks

**Comment by bhj8** [comment]
As far as I know, mid changes their request content. Some parameters have been modified, just update the parameters in these requests to the latest ones.
Sorry, I can't fix this right away due to working hours. I hope some buddies will come forward 😊

**Comment by askime** [comment]
> I think its related to我认为它与 "session_id" => "2fb980f65e5c9a77c96ca01f2c242cf6",“session_id” => “2fb980f65e5c9a77c96ca01f2c242cf6”， "data" => [ “数据” => [ "version" => "1077969938624553050",“版本” => “1077969938624553050”， "id" => "938956540159881230",“id” => “938956540159881230”，
> 
> how to get version, id etc? thanks a lot如何获取版本，ID等？多谢

old: 1077969938624553050 
new : 1118961510123847772
